# Generated by Django 6.0 on 2025-12-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Amazon product link-ah inga paste pannunga', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_path',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
