# Generated by Django 6.0 on 2025-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_amazon_url_product_image_url_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, default='4.0', max_length=10, null=True),
        ),
    ]
