# Generated by Django 6.0 on 2025-12-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_rating_remove_product_reviews_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier_order_id',
        ),
    ]
