# Generated by Django 6.0 on 2025-12-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Amazon link-ah paste pannunga', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deal_type',
            field=models.CharField(choices=[('top_deal', 'Top Deal'), ('best_seller', 'Best Seller'), ('clearance', 'Stock Clearance')], default='top_deal', max_length=20),
        ),
    ]
