# Generated by Django 6.0 on 2025-12-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_bulk_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='qc_passed',
            field=models.BooleanField(default=False),
        ),
    ]
