# Generated by Django 6.0 on 2025-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_ai_pricing_active_product_is_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='api_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_name',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
