# Generated by Django 6.0 on 2025-12-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_api_response_order_supplier_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='ai_pricing_active',
        ),
        migrations.AddField(
            model_name='order',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='print_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_product_id',
            field=models.CharField(blank=True, help_text='Global Product ID (Printify)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='printify_variant_id',
            field=models.CharField(blank=True, help_text='Global Variant ID (Printify)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='printrove_variant_id',
            field=models.CharField(blank=True, help_text='India Variant ID (Printrove)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('RTO', 'RTO (Returned)')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
